name: Celltype Explorer Feedback
description: Give us some feedback on the Celltype Explorer.
title: "[FEEDBACK]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give us feedback! It would be helpful if you could provide some details about your experience with the Connectome presentation.

  - type: textarea
    id: feedback-description
    attributes:
      label: Description
      description: Please provide your feedback. No matter what type of feedback you have, the more detail you provide, the better we can react to your suggestion.
      placeholder: |
        If you want to report a problem, please describe what happened, what you expected to happen, and anything that can help us understand what went wrong.

        Also for any other type of feedback: the more detail you provide, the better.

      render: markdown
    validations:
      required: true
  
  - type: input
    id: url
    attributes:
      label: URL
      description: URL you want to comment on or where the issue occurred
      placeholder: https://reiserlab.github.io/celltype-explorer-drosophila-male-cns/types/Dm4.html
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Web Browser
      description: Which browser did you use to look at the page? Let us know the version, if you can.
      placeholder: Firefox, Safari, Chrome, something else?
    validations:
      required: false

  - type: input
    id: dataset
    attributes:
      label: Dataset and version
      description: Name of the dataset, visible at the bottom of each page
      placeholder: e.g., male-cns:v0.9, optic-lobe:v1.1, flywire-fafb:v783b
    validations:
      required: false

  - type: input
    id: neuview-version
    attributes:
      label: neuView Version
      description: Version of neuView, visible on the bottom of each page
      placeholder: e.g., v2.1.0, main branch
    validations:
      required: false

  - type: input
    id: snapshot-date
    attributes:
      label: Snapshot Generated On
      description: Date and time when the snapshot was generated, visible at the bottom of each page
      placeholder: e.g., 2025-10-01 21:42
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context here
      placeholder: Screenshots, logs, or any other relevant information
    validations:
      required: false
